# Weather Data 

http://climod2.nrcc.cornell.edu/

**Product:** Daily Data Listing 

**Start Date:** 2022-01-01 

**End Date:** 2025-06-30

**Metrics**
- Highest temp 
- Lowest temp 
- Avg. Temp
- Max Precipitation
- Max snow fall

**Station:** NYC Central Park

In [5]:
# import neccessary libraries 
import pandas as pd
import regex as re
import numpy as np
import os

In [7]:
os.getcwd()

'/Users/dirkhartog/Desktop/CUNY_MSDS/DATA_698/py_Notebooks'

In [9]:
# Read in xslx file 
weather_file = pd.read_csv('https://raw.githubusercontent.com/D-hartog/DATA698/refs/heads/main/Project%20files/Data/Weather_data%20-%20sheet1.csv')

weather_file.head()

,Date,MaxTemperature,MinTemperature,AvgTemperature,Precipitation,Snowfall,SnowDepth
0,2022-01-01,56,50,53.0,0.79,0,0
1,2022-01-02,59,37,48.0,0.04,0,0
2,2022-01-03,37,22,29.5,0,0,0
3,2022-01-04,34,19,26.5,0,0,0
4,2022-01-05,47,31,39.0,0.23,0,0

In [43]:
weather_file.replace("T", np.nan)

,Date,MaxTemperature,MinTemperature,AvgTemperature,Precipitation,Snowfall,SnowDepth
0,2022-01-01,56,50,53.0,0.79,0,0
1,2022-01-02,59,37,48.0,0.04,0,0
2,2022-01-03,37,22,29.5,0,0,0
3,2022-01-04,34,19,26.5,0,0,0
4,2022-01-05,47,31,39.0,0.23,0,0
...,...,...,...,...,...,...,...
1303,2025-07-27,84,73,78.5,NaN,0,0
1304,2025-07-28,94,76,85.0,0,0,0
1305,2025-07-29,97,78,87.5,0,0,0
1306,2025-07-30,95,75,85.0,0.28,0,0
1307,2025-07-31,89,65,77.0,0.32,0,0

In [47]:
# Replace any value "T" with NA

weather_file = weather_file.replace("T", np.nan)
weather_file.head()

,Date,MaxTemperature,MinTemperature,AvgTemperature,Precipitation,Snowfall,SnowDepth
0,2022-01-01,56,50,53.0,0.79,0,0
1,2022-01-02,59,37,48.0,0.04,0,0
2,2022-01-03,37,22,29.5,0,0,0
3,2022-01-04,34,19,26.5,0,0,0
4,2022-01-05,47,31,39.0,0.23,0,0

In [63]:
# View rows with NA value
weather_file[weather_file["Precipitation"].isna()]

,Date,MaxTemperature,MinTemperature,AvgTemperature,Precipitation,Snowfall,SnowDepth
10,2022-01-11,24,15,19.5,NaN,NaN,NaN
23,2022-01-24,36,26,31.0,NaN,NaN,NaN
49,2022-02-19,40,23,31.5,NaN,NaN,0
71,2022-03-13,35,22,28.5,NaN,NaN,0
73,2022-03-15,68,46,57.0,NaN,0,0
...,...,...,...,...,...,...,...
1292,2025-07-16,87,77,82.0,NaN,0,0
1293,2025-07-17,90,75,82.5,NaN,0,0
1295,2025-07-19,81,69,75.0,NaN,0,0
1296,2025-07-20,88,75,81.5,NaN,0,0
1303,2025-07-27,84,73,78.5,NaN,0,0

In [65]:
#T: Trace amount- Less than 0.01" precipitation; less than 0.1" snowfall; less than 1" snow depth.

# FIll in NA values based on above criteria 

weather_file["Precipitation"] =  weather_file["Precipitation"].fillna(0.009)
weather_file["Snowfall"] =  weather_file["Snowfall"].fillna(0.09)
weather_file["SnowDepth"] =  weather_file["SnowDepth"].fillna(0.9)

In [67]:
weather_file.isna().sum()

Date              0
MaxTemperature    0
MinTemperature    0
AvgTemperature    0
Precipitation     0
Snowfall          0
SnowDepth         0
dtype: int64

In [71]:
weather_file.to_csv('/Users/dirkhartog/Desktop/CUNY_MSDS/DATA_698/Data/Weather_data_cleaned.csv', index=False)